version: "3"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: clair
      POSTGRES_PASSWORD: clair
      POSTGRES_DB: clair

  clair:
    image: quay.io/projectquay/clair:4.9.0
    ports:
      - "6060:6060"
    volumes:
      - ./config.yaml:/config/config.yaml
    command: ["-conf", "/config/config.yaml"]
    depends_on:
      - postgres
